"""Open Credit Enablement Network (OCEN) Adapter.

Models the data adapter for mapping MSME Financial Health Scores into
OCEN-compliant Loan Referral and Credit Offer payloads.
"""

from __future__ import annotations

import logging
from pydantic import BaseModel, Field

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("OCENAdapter")


class HealthScoreSummary(BaseModel):
    overall_score: float = Field(..., alias="overallScore")
    risk_band: str = Field(..., alias="riskBand")
    confidence_band: str = Field(..., alias="confidenceBand")
    stability_dimension: float | None = Field(..., alias="stabilityDimension")
    cashflow_dimension: float | None = Field(..., alias="cashflowDimension")


class RecommendedTerms(BaseModel):
    max_suggested_credit_limit: float = Field(..., alias="maxSuggestedCreditLimit")
    recommended_tenor_months: int = Field(..., alias="recommendedTenorMonths")
    interest_rate_cap_annual: float = Field(..., alias="interestRateCapAnnual")
    pricing_tier: str = Field(..., alias="pricingTier")


class OCENLoanReferralPayload(BaseModel):
    """OCEN-style Loan Referral Handoff payload.

    Models the payload used by Loan Service Providers (LSPs) to transmit computed credit health details
    to digital lenders on the OCEN protocol network.
    """
    ocen_protocol_version: str = Field("4.0.0-rc1", alias="ocenProtocolVersion", description="OCEN API specification version.")
    borrower_id: str = Field(..., alias="borrowerId", description="LSP borrower identifier.")
    loan_application_ref: str = Field(..., alias="loanApplicationRef", description="Reference ID generated by the LSP portal.")
    consent_ref: str | None = Field(None, alias="consentRef", description="Associated Account Aggregator consent token.")
    health_score_summary: HealthScoreSummary = Field(..., alias="healthScoreSummary")
    recommended_terms: RecommendedTerms = Field(..., alias="recommendedTerms")


def generate_ocen_payload(
    msme_id: str,
    score_result: dict,
    consent_token: str | None = None
) -> OCENLoanReferralPayload:
    """Translates a composite ScoreResponse into an OCEN LSP loan offer reference payload."""
    overall = score_result["overall_score"]
    
    # Pricing/Term inferences based on risk bands
    if overall >= 80.0:
        limit = 500000.0
        tenor = 12
        rate = 11.5
        tier = "Prime"
    elif overall >= 60.0:
        limit = 200000.0
        tenor = 6
        rate = 14.5
        tier = "Standard"
    else:
        limit = 0.0
        tenor = 0
        rate = 18.0
        tier = "Subprime/Decline"

    summary = HealthScoreSummary(
        overallScore=overall,
        riskBand="Low" if overall >= 80 else ("Medium" if overall >= 60 else "High"),
        confidenceBand=score_result["confidence_band"],
        stabilityDimension=score_result["dimension_scores"].get("stability"),
        cashflowDimension=score_result["dimension_scores"].get("cashflow")
    )

    terms = RecommendedTerms(
        maxSuggestedCreditLimit=limit,
        recommendedTenorMonths=tenor,
        interestRateCapAnnual=rate,
        pricingTier=tier
    )

    import uuid
    app_ref = f"LN-APP-{uuid.uuid4().hex[:8].upper()}"

    return OCENLoanReferralPayload(
        ocenProtocolVersion="4.0.0-rc1",
        borrowerId=msme_id,
        loanApplicationRef=app_ref,
        consentRef=consent_token,
        healthScoreSummary=summary,
        recommendedTerms=terms
    )


def push_to_lsp(payload: OCENLoanReferralPayload) -> dict:
    """Mocks transmitting the OCEN credit recommendation payload back to the LSP network.

    In a production system, this pushes the score card to the OCEN Loan Service Provider Gateway,
    initiating the lender's final automated quote generation.
    """
    logger.info(f"Pushing OCEN Loan Referral for Borrower {payload.borrower_id} (Limit Ref: {payload.recommended_terms.max_suggested_credit_limit})")
    
    # Return mock API transaction receipt
    import uuid
    import time
    return {
        "ocenTxId": f"TXN-OCEN-{uuid.uuid4().hex[:12].upper()}",
        "timestamp": int(time.time()),
        "status": "QUEUED_FOR_OFFERS",
        "payload_received_hash": hash(payload.json())
    }
